"""room members

Revision ID: 2de7f21c1d9f
Revises: ce037065567e
Create Date: 2024-03-28 22:40:31.000752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2de7f21c1d9f'
down_revision = 'ce037065567e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_room', schema=None) as batch_op:
        batch_op.alter_column('creator_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'chat_room', ['room_id'], ['id'])
        batch_op.drop_column('room')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('room_id')

    with op.batch_alter_table('chat_room', schema=None) as batch_op:
        batch_op.alter_column('creator_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
